server:
  port: 80

feign:
  hystrix:
    enabled: true #客户端支持hystrix

eureka:
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
